### ISSUE TITLE
Crash on every 3rd or 4th capture

### ISSUE THREAD

**Issue by nitishrana28** [romainmenke/SimpleCam#1]
Getting this crash : 

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -_referenceData64 only defined for abstract class.  Define -[NSTemporaryObjectID_default _referenceData64]!'  
  
Adding screenshot which might help :  

![screen shot 2017-07-05 at 5 44 55 pm](https://user-images.githubusercontent.com/1484780/27863901-d3e41c3c-61a9-11e7-9145-11ac2aa88723.png)

**Comment by romainmenke** [comment]
I was able to reproduce this. Code also needs to be updated to swift 3. 
Will take a closer look

**Comment by nitishrana28** [comment]
Actually I was able to avoid the crash by putting saveImage function in managedContext block and wait (SaveImages.swift extension). But please check if this can be handled more efficiently.  

```
self.managedContext?.performAndWait {
                // send to save function
                self.saveImage(imageData, thumbnailData: thumbnailData, date: date)
            }
```

**Comment by romainmenke** [comment]
The underlying issue is the `coreDataQueue` which is a concurrent queue protected by barrier ops. These however fail horribly.

Init the `coreDataQueue` like this and it will work much better.
`let coreDataQueue = DispatchQueue(label: "coreDataQueue")`

**Comment by romainmenke** [comment]
should be ok now
