### ISSUE TITLE
not save all images sometime some dummy rows created 

### ISSUE THREAD

**Issue by Sushobhitbuiltbyblank** [romainmenke/SimpleCam#3]
I am trying to implement your library.you have done a great work but sometime I have noticed that this app show some blank rows and some time got crashed as well. when i add images by capturing. after capturing or clicked on loading app got crashed. can you fix that. I want to use that in my app if all well.

**Comment by romainmenke** [comment]
Yeah haven't maintained it past Swift 2 and is pretty much broken now. Might find some time in the future to take a look.

**Comment by Sushobhitbuiltbyblank** [comment]
ok thanks for response.
